
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acloud?serverTimezone=GMT%2B8
    username: root
    password: zhang962464.
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
mybatis-plus:
  type-aliases-package: com.zhweb.entity
  mapper-locations: classpath\:mapper/*.xml
server:
  port: 8081
logging:
  config: classpath:logback.xml